package enumeration;

public enum Emploi {

	ACHETEUR("Acheteur"),
	ACHETEUR_D_ESPACES_PUB("Acheteur d'espaces pub"),
	ACHETEUR_INFORMATIQUE_ET_TELECOM("Acheteur Informatique Et Télécom"),
	ACTUAIRE("Actuaire"),
	ADJOINT_ADMINISTRATIF("Adjoint administratif"),
	ADJOINT_ADMINISTRATIF_D_ADMINISTRATION_CENTRALE("Adjoint administratif d'administration centrale"),
	ADJOINT_ADMINISTRATIF_TERRITORIAL("Adjoint administratif territorial"),
	ADJOINT_TECHNIQUE_DE_RECHERCHE_ET_DE_FORMATION("Adjoint technique de recherche et de formation"),
	ADJOINT_TERRITORIAL_D_ANIMATION("Adjoint territorial d'animation"),
	ADMINISTRATEUR_BASE_DE_DONNEES("Administrateur base de données"),
	ADMINISTRATEUR_DE_BASES_DE_DONNEES("Administrateur De Bases De Données"),
	ADMINISTRATEUR_DE_BIENS("Administrateur de biens"),
	ADMINISTRATEUR_DE_RESEAU("Administrateur De Réseau"),
	ADMINISTRATEUR_JUDICIAIRE("Administrateur judiciaire"),
	AFFRETEUR("Affréteur"),
	AGENT_ADMINISTRATIF_ET_AGENT_DES_SERVICES_TECHNIQUES("Agent administratif et agent des services techniques"),
	AGENT_D_ENTRETIEN_D_ASCENSEURS("Agent d'entretien d'ascenseurs"),
	AGENT_D_EXPLOITATION_DES_EQUIPEMENTS_AUDIOVISUELS("Agent d'exploitation des équipements audiovisuels"),
	AGENT_DE_MAINTENANCE_EN_MECANIQUE("Agent de maintenance en mécanique"),
	AGENT_DE_MAITRISE("Agent de maîtrise"),
	AGENT_DE_POLICE_MUNICIPALE("Agent de police municipale"),
	AGENT_DE_RESERVATION("Agent de réservation"),
	AGENT_DES_SERVICES_TECHNIQUES_D_ADMINISTRATION_CENTRALE("Agent des services techniques d'administration centrale"),
	AGENT_DES_SERVICES_TECHNIQUES_DE_PREFECTURE("Agent des services techniques de préfecture"),
	AGENT_DES_SYSTEMES_D_INFORMATION_ET_DE_COMMUNICATION("Agent des systèmes d'information et de communication"),
	AGENT_IMMOBILIER("Agent immobilier"),
	AGENT_SPECIALISE_DE_POLICE_TECHNIQUE_ET_SCIENTIFIQUE("Agent spécialisé de police technique et scientifique"),
	AGENT_TECHNIQUE_DE_RECHERCHE_ET_DE_FORMATION("Agent technique de recherche et de formation"),
	AIDE_COMPTABLE("Aide comptable"),
	AIDE_DE_LABORATOIRE("Aide de laboratoire"),
	AIDE_MEDICO_PSYCHOLOGIQUE("Aide médico-psychologique"),
	AIDE_SOIGNANT("Aide soignant"),
	AIDE_TECHNIQUE_DE_LABORATOIRE("Aide technique de laboratoire"),
	AMBULANCIER("Ambulancier"),
	ANALYSTE_D_EXPLOITATION("Analyste D'Exploitation"),
	ANALYSTE_FINANCIER("Analyste financier"),
	ANALYSTE_PROGRAMMEUR("Analyste programmeur"),
	ANIMATEUR("Animateur"),
	ANIMATEUR_DE_CLUB_DE_VACANCES("Animateur de club de vacances"),
	ANIMATEUR_DE_FORMATION("Animateur de formation"),
	ANIMATEUR_ENVIRONNEMENT("animateur environnement"),
	ANIMATEUR_SOCIOCULTUREL("Animateur socioculturel"),
	ANTIQUAIRE("Antiquaire"),
	ARCHEOLOGUE("Archéologue"),
	ARCHITECTE("Architecte"),
	ARCHITECTE_D_INTERIEUR("Architecte d'intérieur"),
	ARCHITECTE_DE_BASES_DE_DONNEES("Architecte De Bases De Données"),
	ARCHITECTE_DE_RESEAU("Architecte De Réseau"),
	ARCHITECTE_DE_SYSTEME_D_INFORMATION("Architecte De Système D'Information"),
	ARCHITECTE_MATERIEL("Architecte Matériel"),
	ARCHIVISTE("Archiviste"),
	ARTISTE_PEINTRE("Artiste-peintre"),
	ASSISTANT_DE_CONSERVATION("Assistant de conservation"),
	ASSISTANT_DE_JUSTICE("Assistant de justice"),
	ASSISTANT_DE_RESSOURCES_HUMAINES("Assistant de ressources humaines"),
	ASSISTANT_DE_SERVICE_SOCIAL("Assistant de service social"),
	ASSISTANT_DES_BIBLIOTHEQUES("Assistant des bibliothèques"),
	ASSISTANT_INGENIEUR("Assistant ingénieur"),
	ASSISTANT_MEDICO_TECHNIQUE("Assistant médico-technique"),
	ASSISTANT_SOCIO_EDUCATIF("Assistant socio-éducatif"),
	ASSISTANT_SON("Assistant son"),
	ASSISTANT_VETERINAIRE("Assistant vétérinaire"),
	ASSISTANTE_DE_GESTION_PMI_PME("Assistante de gestion PMI/PME"),
	ASSISTANTE_MATERNELLE("Assistante maternelle"),
	ASSISTANTE_SOCIALE("Assistante sociale"),
	ASTRONOME("Astronome"),
	ATTACHE_D_ADMINISTRATION_ET_D_INTENDANCE("Attaché d'administration et d'intendance"),
	ATTACHE_D_ADMINISTRATION_HOSPITALIERE("Attaché d'administration hospitalière"),
	ATTACHE_D_ADMINISTRATION_CENTRALE("Attaché d'administration centrale"),
	ATTACHE_D_ADMINISTRATION_SCOLAIRE_ET_UNIVERSITAIRE("Attaché d'administration scolaire et universitaire"),
	ATTACHE_DE_CONSERVATEUR_DE_PATRIMOINE("Attaché de conservateur de patrimoine"),
	ATTACHE_DE_POLICE("Attaché de police"),
	ATTACHE_DE_PREFECTURE("Attaché de préfecture"),
	ATTACHE_DE_PRESSE("Attaché de presse"),
	AUDITEUR_INFORMATIQUE("Auditeur Informatique"),
	AUTEUR_SCENARISTE_MULTIMEDIA("Auteur-scénariste multimédia"),
	AUXILIAIRE_DE_PUERICULTURE("Auxiliaire de puériculture"),
	AUXILIAIRE_DE_VIE_SOCIALE("Auxiliaire de vie sociale"),
	AUXILLIAIRE_DE_VIE("Auxilliaire de vie"),
	AVOCAT("Avocat"),
	BARMAN("Barman"),
	BIBLIOTHECAIRE("Bibliothécaire"),
	BIBLIOTHECAIRE_ADJOINT_SPECIALISE("Bibliothécaire adjoint spécialisé"),
	BIJOUTIER_JOAILLIER("Bijoutier joaillier"),
	BILLETTISTE("Billettiste"),
	BIO_INFORMATICIEN("Bio-informaticien"),
	BIOLOGISTE_VETERINAIRE_PHARMACIEN("Biologiste, Vétérinaire, Pharmacien"),
	BOBINIER_DE_LA_CONSTRUCTION_ELECTRIQUE("Bobinier de la construction électrique"),
	BOUCHER("Boucher"),
	BOULANGER("Boulanger"),
	BRASSEUR_MALTEUR("Brasseur malteur"),
	BRONZIER("Bronzier"),
	BÛCHERON("Bûcheron"),
	CADREUR("Cadreur"),
	CAPITAINE_DE_SAPEUR_POMPIER("Capitaine de Sapeur-Pompier"),
	CARRELEUR("Carreleur"),
	CARROSSIER_REPARATEUR("Carrossier réparateur"),
	CAVISTE("Caviste"),
	CHARCUTIER_TRAITEUR("Charcutier-traiteur"),
	CHARGE_DE_CLIENTELE("Chargé de clientèle"),
	CHARGE_DE_REFERENCEMENT("Chargé De Référencement"),
	CHARGE_DE_RELATIONS_PUBLIQUES("Chargé de relations publiques"),
	CHARPENTIER("Charpentier"),
	CHAUDRONNIER("Chaudronnier"),
	CHEF_D_ATELIER_DES_INDUSTRIES_GRAPHIQUES("Chef d'atelier des industries graphiques"),
	CHEF_DE_CHANTIER("Chef de chantier"),
	CHEF_DE_COMPTOIR("Chef de comptoir"),
	CHEF_DE_FABRICATION("Chef de fabrication"),
	CHEF_DE_PRODUITS_VOYAGES("Chef de produits voyages"),
	CHEF_DE_PROJET_PROJECT_MANAGER("Chef De Projet - Project Manager"),
	CHEF_DE_PROJET_INFORMATIQUE("Chef de projet informatique"),
	CHEF_DE_PROJET_MULTIMEDIA("Chef de projet multimedia"),
	CHEF_DE_PUBLICITE("Chef de publicité"),
	CHEF_DE_RAYON("Chef de rayon"),
	CHEF_DE_SERVICE_DE_POLICE_MUNICIPALE("Chef de service de Police municipale"),
	CHEF_OPERATEUR("Chef opérateur"),
	CHERCHEUR("Chercheur"),
	CHERCHEUR_EN_INFORMATIQUE("Chercheur En Informatique"),
	CHIRURGIEN_DENTISTE("Chirurgien-dentiste"),
	CHOCOLATIER_CONFISEUR("Chocolatier confiseur"),
	CLERC_DE_NOTAIRE("Clerc de notaire"),
	COIFFEUR("Coiffeur"),
	COMEDIEN("Comédien"),
	COMMIS_DE_CUISINE("Commis de cuisine"),
	COMMISSAIRE_DE_POLICE("Commissaire de police"),
	COMMISSAIRE_PRISEUR("Commissaire priseur"),
	COMPORTEMENTALISTE("comportementaliste"),
	COMPTABLE("Comptable"),
	CONCEPTEUR_DE_JEUX_ELECTRONIQUES("Concepteur De Jeux Électroniques"),
	CONCEPTEUR_REDACTEUR("Concepteur rédacteur"),
	CONCIERGE_D_HÔTEL("Concierge d'hôtel"),
	CONDUCTEUR("Conducteur"),
	CONDUCTEUR_D_APPAREILS("Conducteur d'appareils"),
	CONDUCTEUR_D_AUTOBUS("Conducteur d'autobus"),
	CONDUCTEUR_D_AUTOMOBILE("Conducteur d'automobile"),
	CONDUCTEUR_D_ENGINS_EN_BTP("Conducteur d'engins en BTP"),
	CONDUCTEUR_DE_MACHINE_A_IMPRIMER_D_EXPLOITATION_COMPLEXE("Conducteur de machine à imprimer d'exploitation complexe"),
	CONDUCTEUR_DE_MACHINE_A_IMPRIMER_SIMPLE("Conducteur de machine à imprimer simple"),
	CONDUCTEUR_DE_MACHINES("Conducteur de machines"),
	CONDUCTEUR_DE_MACHINES_AGRO("Conducteur de machines agro"),
	CONDUCTEUR_DE_STATION_D_EPURATION("Conducteur de station d'épuration"),
	CONDUCTEUR_DE_TAXI("Conducteur de taxi"),
	CONDUCTEUR_DE_TRAIN("conducteur de train"),
	CONDUCTEUR_DE_TRAVAUX("Conducteur de travaux"),
	CONDUCTEUR_ROUTIER("Conducteur routier"),
	CONSEIL_EN_ASSISTANCE_A_MAITRISE_D_OUVRAGE("Conseil En Assistance À Maitrise D'Ouvrage"),
	CONSEILLER_D_INSERTION_ET_DE_PROBATION("Conseiller d'insertion et de probation"),
	CONSEILLER_D_ORIENTATION("Conseiller d'orientation"),
	CONSEILLER_D_ORIENTATION_PSYCHOLOGUE("Conseiller d'orientation-psychologue"),
	CONSEILLER_EN_DEVELOPPEMENT_TOURISTIQUE("Conseiller en développement touristique"),
	CONSEILLER_EN_ECONOMIE_SOCIALE_ET_FAMILIALE("Conseiller en économie sociale et familiale"),
	CONSEILLER_SOCIO_EDUCATIF("Conseiller socio-éducatif"),
	CONSEILLER_TERRITORIAL_DES_ACTIVITES_PHYSIQUES_ET_SPORTIVES("Conseiller territorial des activités physiques et sportives"),
	CONSEILLERS_PRINCIPAUX_D_EDUCATION("Conseillers principaux d'éducation"),
	CONSERVATEUR_DE_BIBLIOTHEQUE("Conservateur de bibliothèque"),
	CONSERVATEUR_DU_PATRIMOINE("Conservateur du patrimoine"),
	CONSULTANT_COMMUNICATION_RESEAUX("Consultant Communication & Réseaux"),
	CONSULTANT_E_BUSINESS("Consultant E-Business"),
	CONSULTANT_EN_CONDUITE_DU_CHANGEMENT("Consultant En Conduite Du Changement"),
	CONSULTANT_EN_E_LEARNING("Consultant En E-Learning"),
	CONSULTANT_EN_GESTION_DE_LA_RELATION_CLIENT("Consultant En Gestion De La Relation Client"),
	CONSULTANT_EN_ORGANISATION_DES_SYSTEMES_D_INFORMATION("Consultant En Organisation Des Systèmes D'Information"),
	CONSULTANT_EN_TECHNOLOGIES("Consultant En Technologies"),
	CONSULTANT_ERP("Consultant Erp"),
	CONSULTANT_FONCTIONNEL("Consultant Fonctionnel"),
	CONSULTANT_INFORMATIQUE("Consultant Informatique"),
	CONTRÔLEUR_AERIEN("Contrôleur aérien"),
	CONTRÔLEUR_DE_GESTION("Contrôleur de gestion"),
	CONTRÔLEUR_DE_TRAVAUX("Contrôleur de travaux"),
	CONTRÔLEUR_DES_SERVICES_TECHNIQUES_DU_MATERIEL("Contrôleur des services techniques du matériel"),
	CONTRÔLEUR_DES_SYSTEMES_D_INFORMATION_ET_DE_COMMUNICATION("Contrôleur des systèmes d'information et de communication"),
	CONTRÔLEUR_DU_TRAVAIL("Contrôleur du travail"),
	CONTRÔLEUR_EN_ELECTRICITE_ET_ELECTRONIQUE("Contrôleur en électricité et électronique"),
	CONVOYEUR_DE_FONDS("Convoyeur de fonds"),
	COORDINATRICE_DE_CRECHES("Coordinatrice de crèches"),
	CORRECTEUR("Correcteur"),
	COSTUMIER_HABILLEUR("Costumier-habilleur"),
	COURTIER_D_ASSURANCES("Courtier d'assurances"),
	COUVREUR("Couvreur"),
	CREATEUR_DE_PARFUM("Créateur de parfum"),
	CUISINIER("Cuisinier"),
	CYBERDOCUMENTALISTE("Cyberdocumentaliste"),
	DANSEUR("Danseur"),
	DECORATEUR_SCENOGRAPHE("Décorateur-scénographe"),
	DELEGUE_MEDICAL("Délégué médical"),
	DEMENAGEUR("Déménageur"),
	DEMOGRAPHE("Démographe"),
	DEPANNEUR_TV_ELECTROMENAGER("Dépanneur tv électroménager"),
	DESIGNER_AUTOMOBILE("Designer automobile"),
	DESSINATEUR_DE_PRESSE("Dessinateur de presse"),
	DESSINATEUR_INDUSTRIEL("Dessinateur industriel"),
	DETECTIVE_PRIVE("Détective privé"),
	DEVELOPPEUR("Développeur"),
	DIETETICIEN("Diététicien"),
	DIRECTEUR_ARTISTIQUE("Directeur artistique"),
	DIRECTEUR_COMMERCIAL("Directeur Commercial"),
	DIRECTEUR_D_ETABLISSEMENT_SOCIAL_ET_MEDICO_SOCIAL("Directeur d'établissement social et médico-social"),
	DIRECTEUR_D_HÔPITAL("Directeur d'hôpital"),
	DIRECTEUR_D_ETABLISSEMENT_D_ENSEIGNEMENT_ARTISTIQUE("Directeur d'établissement d'enseignement artistique"),
	DIRECTEUR_D_ETABLISSEMENT_SANITAIRE_ET_SOCIAL("Directeur d'établissement sanitaire et social"),
	DIRECTEUR_D_OFFICE_DE_TOURISME("Directeur d'office de tourisme"),
	DIRECTEUR_DE_COLLECTION("Directeur de collection"),
	DIRECTEUR_DE_PARC_NATUREL("Directeur de parc naturel"),
	DIRECTEUR_DE_PROJET("Directeur De Projet"),
	DIRECTEUR_DE_RESSOURCES_HUMAINES("Directeur de ressources humaines"),
	DIRECTEUR_DES_SOINS("Directeur des soins"),
	DIRECTEUR_DES_SYSTEMES_D_INFORMATION("Directeur Des Systèmes D'Information"),
	DIRECTEUR_TECHNIQUE("Directeur Technique"),
	DOCKER("Docker"),
	DOCUMENTALISTE("Documentaliste"),
	DOUANIER("Douanier"),
	EBENISTE("Ebéniste"),
	EBOUEUR("Eboueur"),
	ECO_CONSEILLER("Eco-conseiller"),
	ECOTOXICOLOGUE("Ecotoxicologue"),
	EDUCATEUR_DE_JEUNES_ENFANTS("Educateur de jeunes enfants"),
	EDUCATEUR_SPECIALISE("Educateur spécialisé"),
	EDUCATEUR_SPORTIF("Educateur sportif"),
	EDUCATEUR_TECHNIQUE_SPECIALISE("Educateur technique spécialisé"),
	EDUCATEUR_TERRITORIAL_DES_ACTIVITES_PHYSIQUES_ET_SPORTIVES("Educateur territorial des activités physiques et sportives"),
	ELECTRICIEN_DE_MAINTENANCE("Electricien de maintenance"),
	ELECTRICIEN_DU_BATIMENT("Electricien du bâtiment"),
	ELECTRICIEN_ELECTRONICIEN_AUTO("Electricien électronicien auto"),
	EMPLOYE_DE_GROUPAGE("Employé de groupage"),
	EMPLOYE_DE_RESTAURATION_RAPIDE("Employé de restauration rapide"),
	EMPLOYES_DU_HALL_DES_HÔTELS("Employés du hall des hôtels"),
	ENCADREUR("Encadreur"),
	ENSEIGNANT_CHERCHEUR("Enseignant Chercheur"),
	ENTRAINEUR_SPORTIF("Entraîneur sportif"),
	ERGONOME("Ergonome"),
	ERGOTHERAPEUTE("Ergothérapeute"),
	ESTHETICIENNE_COSMETICIENNE("Esthéticienne-cosméticienne"),
	ETALAGISTE_DECORATEUR("Etalagiste décorateur"),
	ETHNOLOGUE("Ethnologue"),
	EXPERT_AUTOMOBILE("Expert automobile"),
	EXPERT_COMPTABLE("Expert comptable"),
	EXPERT_EN_SECURITE_INFORMATIQUE("Expert En Sécurité Informatique"),
	FACTEUR_INSTRUMENTAL("Facteur instrumental"),
	FEMME_DE_CHAMBRE_OU_VALET_DE_CHAMBRE("Femme de chambre ou valet de chambre"),
	FLEURISTE("Fleuriste"),
	FORFAITISTE("Forfaitiste"),
	FORMATEUR_EN_INFORMATIQUE("Formateur En Informatique"),
	GAME_DESIGNER("Game designer"),
	GARCON_DE_CAFE("Garçon de café"),
	GARDE_DU_CORPS("Garde du corps"),
	GARDE_CHAMPETRE("Garde-champêtre"),
	GARDIEN_D_IMMEUBLE("Gardien d'immeuble"),
	GARDIEN_DE_LA_PAIX("Gardien de la paix"),
	GENDARME("Gendarme"),
	GEOGRAPHE("Géographe"),
	GEOLOGUE("Géologue"),
	GEOMETRE_TOPOGRAPHE("Géomètre topographe"),
	GERANT_D_HÔTEL("Gérant d'hôtel"),
	GESTIONNAIRE_DE_PARC_MICRO_INFORMATIQUE("Gestionnaire De Parc Micro-Informatique"),
	GRAPHISTE_MULTIMEDIA("Graphiste multimédia"),
	GREFFIER("Greffier"),
	GUICHETETIER("Guichetetier"),
	GUIDE_ACCOMPAGNATEUR("Guide accompagnateur"),
	GUIDE_DE_HAUTE_MONTAGNE("Guide de haute montagne"),
	GUIDE_INTERPRETE("Guide Interprète"),
	HORICULTEUR("Horiculteur"),
	HOT_LINER_TECHNICIEN_HELP_DESK("Hot-Liner Technicien Help-Desk"),
	HÔTESSE_D_ACCUEIL("Hôtesse d'accueil"),
	HÔTESSE_DE_L_AIR("Hôtesse de l'air"),
	HOTLINER("Hotliner"),
	HUISSIER_DE_JUSTICE("Huissier de justice"),
	ICONOGRAPHE("Iconographe"),
	INFIRMIER("Infirmier"),
	INFIRMIER_ANESTHESISTE_DIPLÔME_D_ETAT("Infirmier anesthésiste diplômé d'Etat"),
	INFIRMIER_CHEF("Infirmier chef"),
	INFIRMIER_DE_BLOC_OPERATOIRE_DIPLÔME_D_ETAT("Infirmier de bloc opératoire diplômé d'Etat"),
	INFIRMIER_DIPLÔME_D_ETAT("Infirmier diplômé d'Etat"),
	INFIRMIERE("Infirmiere"),
	INGENIEUR_AGROALIMENTAIRE("Ingénieur agroalimentaire"),
	INGENIEUR_COMMERCIAL("Ingénieur Commercial"),
	INGENIEUR_D_ETUDES_SANITAIRES("Ingénieur d'études sanitaires"),
	INGENIEUR_D_ETUDE_ET_DE_DEVELOPPEMENT("Ingénieur d'étude et de développement"),
	INGENIEUR_D_ETUDES("Ingénieur d'études"),
	INGENIEUR_DE_CONSTRUCTION_DE_RESEAUX("Ingénieur De Construction De Réseaux"),
	INGENIEUR_DE_LABORATOIRE("Ingénieur de laboratoire"),
	INGENIEUR_DE_PRODUCTION("Ingénieur de production"),
	INGENIEUR_DE_RECHERCHE("Ingénieur de recherche"),
	INGENIEUR_DE_RECHERCHE_PRODUIT("Ingénieur de recherche produit"),
	INGENIEUR_DEPLOIEMENT_DE_RESEAU("Ingénieur Déploiement De Réseau"),
	INGENIEUR_DES_SERVICES_TECHNIQUES_DU_MATERIEL("Ingénieur des services techniques du matériel"),
	INGENIEUR_DES_TRAVAUX("Ingénieur des travaux"),
	INGENIEUR_DEVELOPPEMENT_DE_COMPOSANTS("Ingénieur Développement De Composants"),
	INGENIEUR_DEVELOPPEMENT_LOGICIELS("Ingénieur Développement Logiciels"),
	INGENIEUR_DEVELOPPEMENT_MATERIEL_ELECTRONIQUE("Ingénieur Développement Matériel Électronique"),
	INGENIEUR_DU_GENIE_RURAL_DES_EAUX_ET_FORETS("ingénieur du génie rural des eaux et forêts"),
	INGENIEUR_DU_GENIE_SANITAIRE("Ingénieur du génie sanitaire"),
	INGENIEUR_DU_SON("Ingénieur du son"),
	INGENIEUR_EN_CHEF("Ingénieur en chef"),
	INGENIEUR_INTEGRATION("Ingénieur Intégration"),
	INGENIEUR_LOGISTIQUE("Ingénieur logistique"),
	INGENIEUR_QUALITES_METHODES("Ingénieur Qualités Méthodes"),
	INGENIEUR_SECURITE("Ingénieur Sécurité"),
	INGENIEUR_SUPPORT_TECHNIQUE("Ingénieur Support Technique"),
	INGENIEUR_SYSTEME_RESEAU("Ingénieur système-réseau"),
	INGENIEUR_SYSTEMES_ET_RESEAUX("Ingénieur Systèmes Et Réseaux"),
	INGENIEUR_TECHNICO_COMMERCIAL("Ingénieur Technico-Commercial"),
	INGENIEUR_VALIDATION("Ingénieur Validation"),
	INSPECTEUR_DE_L_ACTION_SANITAIRE_ET_SOCIALE("Inspecteur de l'action sanitaire et sociale"),
	INSPECTEUR_DES_SYSTEMES_D_INFORMATION_ET_DE_COMMUNICATION("Inspecteur des systèmes d'information et de communication"),
	INSPECTEURS_DU_TRAVAIL("Inspecteurs du travail"),
	INSTALLATEUR_EN_TELECOMMUNICATIONS("Installateur en télécommunications"),
	INTEGRATEUR_WEB("Intégrateur Web"),
	INTERPRETE("Interprète"),
	JEUNES_SAPEURS_POMPIERS("Jeunes sapeurs-pompiers"),
	JOURNALISTE("Journaliste"),
	JOURNALISTE_D_ENTREPRISE("Journaliste d'entreprise"),
	JOURNALISTE_RADIO("Journaliste radio"),
	JOURNALISTE_REPORTER("Journaliste reporter"),
	JUGE_D_INSTANCE("Juge d'Instance"),
	JUGE_D_INSTRUCTION("Juge d'instruction"),
	JUGE_DE_GRANDE_INSTANCE("Juge de Grande Instance"),
	JUGE_DE_L_APPLICATION_DES_PEINES("Juge de l'application des peines"),
	JUGE_DE_L_EXECUTION("Juge de l'exécution"),
	JUGE_DES_AFFAIRES_FAMILIALES("Juge des affaires familiales"),
	JUGE_DES_ENFANTS("Juge des enfants"),
	JURISTE_INFORMATIQUE("Juriste Informatique"),
	LES_ADJOINTS_ADMINISTRATIFS_DE_LA_POLICE_NATIONALE("Les adjoints administratifs de la police nationale"),
	LES_ADJOINTS_DE_SECURITE("Les adjoints de sécurité"),
	LES_DIRECTEURS_DE_SERVICES_PENITENTIAIRES("Les Directeurs de services pénitentiaires"),
	LES_GREFFIERS("Les greffiers"),
	LES_PERSONNELS_DE_LA_PROTECTION_JUDICIAIRE_DE_LA_JEUNESSE("Les personnels de la protection judiciaire de la jeunesse"),
	LIBRAIRE("Libraire"),
	LIEUTENANT_DE_POLICE("Lieutenant de police"),
	LIEUTENANT_DE_SAPEURS_POMPIERS("Lieutenant de sapeurs-pompiers"),
	LIVREUR("Livreur"),
	MACON("Maçon"),
	MAGASINIER_EN_CHEF_DES_BIBLIOTHEQUES("Magasinier en chef des bibliothèques"),
	MAGISTRAT("Magistrat"),
	MAITRE_CHIEN("Maître chien"),
	MAITRE_D_HÔTEL("Maître d'hôtel"),
	MAITRE_DE_CONFERENCE("Maître de conférence"),
	MAITRE_OUVRIER_DES_ETABLISSEMENTS_D_ENSEIGNEMENT("Maître ouvrier des établissements d'enseignement"),
	MAITRE_NAGEUR_SAUVETEUR("Maître-nageur sauveteur"),
	MAITRES_DES_ETABLISSEMENTS_D_ENSEIGNEMENT_PRIVES_SOUS_CONTRAT("Maîtres des établissements d'enseignement privés sous contrat"),
	MAJOR_DE_SAPEUR_POMPIER("Major de sapeur-pompier"),
	MANIPULATEUR_D_ELECTRORADIOLOGIE_MEDICALE("Manipulateur d'électroradiologie médicale"),
	MANUTENTIONNAIRE_CARISTE("Manutentionnaire cariste"),
	MAQUETTISTE("Maquettiste"),
	MASSEUR_KINESITHERAPEUTE("Masseur kinésithérapeute"),
	MECANICIEN_2_ROUES("Mécanicien 2 roues"),
	MECANICIEN_AUTO("Mécanicien auto"),
	MEDECIN("Médecin"),
	MEDECIN_DE_L_EDUCATION_NATIONALE("Médecin de l'éducation nationale"),
	MEDECIN_INSPECTEUR_DE_SANTE_PUBLIQUE("Médecin inspecteur de santé publique"),
	MEDECIN_PHARMACIEN_DE_SAPEUR_POMPIER("Médecin pharmacien de Sapeur-pompier"),
	MEDECIN_TERRITORIAL("Médecin Territorial"),
	MEDIA_PLANNER("Média-planner"),
	MEDIATEUR_SOCIAL("Médiateur social"),
	MENUISIER("Menuisier"),
	METEOROLOGUE("Météorologue"),
	METIERS_DE_LA_PRODUCTION("Métiers de la production"),
	MONITEUR_D_AUTO_ECOLE("Moniteur d'auto-école"),
	MONITEUR_DE_SKI("Moniteur de ski"),
	MONITEUR_EDUCATEUR("Moniteur éducateur"),
	MONTEUR("Monteur"),
	MONTEUR_ELECTRICIEN_RESEAU_EDF("Monteur électricien réseau edf"),
	MONTEUR_EN_INSTALLATIONS_THERMIQUES_CHAUFFAGISTE("Monteur en installations thermiques chauffagiste"),
	MUSICIEN("Musicien"),
	NETSURFER("Netsurfer"),
	NOTAIRE("Notaire"),
	OCEANOGRAPHE("Océanographe"),
	OPERATEUR_SUR_MACHINE_DE_PRODUCTION_ELECTRIQUE("Opérateur sur machine de production électrique"),
	OPERATEUR_TERRITORIAL_DES_ACTIVITES_PHYSIQUES_ET_SPORTIVES("Opérateur territorial des activités physiques et sportives"),
	OPERATRICE_DE_SAISIE("Opératrice de saisie"),
	OPTICIEN_LUNETIER("Opticien lunetier"),
	ORTHOPHONISTE("Orthophoniste"),
	ORTHOPTISTE("Orthoptiste"),
	OUVRIER_AGRICOLE("Ouvrier agricole"),
	OUVRIER_D_ENTRETIEN_ET_D_ACCUEIL_OEA_("Ouvrier d'entretien et d'accueil (OEA)"),
	OUVRIER_D_ETAT("Ouvrier d'État"),
	OUVRIER_PROFESSIONNEL_OP_("Ouvrier professionnel (OP)"),
	OUVRIER_PROFESSIONNEL_MAITRE_OUVRIER("Ouvrier professionnel, maître-ouvrier"),
	PARAMETREUR_DE_PROGICIELS("Paramétreur De Progiciels"),
	PATISSIER("Pâtissier"),
	PAYSAGISTE("Paysagiste"),
	PEDICURE_PODOLOGUE("Pédicure podologue"),
	PEINTRE_EN_BATIMENT("Peintre en bâtiment"),
	PEPINIERISTE("Pépinieriste"),
	PERSONNEL_DE_SURVEILLANCE("Personnel de surveillance"),
	PERSONNEL_PENITENTAIRE_D_INSERTION_ET_DE_PROBATION("Personnel pénitentaire d'insertion et de probation"),
	PERSONNEL_TECHNIQUE_DE_L_ADMINISTRATION_PENITENTIAIRE("Personnel technique de l'administration pénitentiaire"),
	PHARMACIEN("Pharmacien"),
	PHARMACIEN_INSPECTEUR_DE_SANTE_PUBLIQUE("Pharmacien inspecteur de santé publique"),
	PHOTOGRAPHE("Photographe"),
	PIGISTE("Pigiste"),
	PILOTE_D_AVION("Pilote d'avion"),
	PLANNEUR_STRATEGIQUE("Planneur stratégique"),
	PLOMBIER("Plombier"),
	POISSONNIER("Poissonnier"),
	PREPARATEUR_EN_PHARMACIE("Préparateur en pharmacie"),
	PREPARATEUR_EN_PHARMACIE_AVEC_PUB("Préparateur en pharmacie avec Pub"),
	PROFESSEUR_AGREGE("Professeur agrégé"),
	PROFESSEUR_CERTIFIE("Professeur certifié"),
	PROFESSEUR_D_ARTS_PLASTIQUES("Professeur d'arts plastiques"),
	PROFESSEUR_D_EDUCATION_PHYSIQUE_ET_SPORTIVE("Professeur d'éducation physique et sportive"),
	PROFESSEUR_D_UNIVERSITE("Professeur d'Université"),
	PROFESSEUR_DE_LYCEE_ET_COLLEGE("Professeur de lycée et collège"),
	PROFESSEUR_DE_LYCEE_PROFESSIONNEL("Professeur de lycée professionnel"),
	PROFESSEUR_DE_MUSIQUE("Professeur de musique"),
	PROFESSEUR_DES_ECOLES("Professeur des écoles"),
	PROFESSEUR_FLE("Professeur FLE"),
	PROJECTIONNISTE("Projectionniste"),
	PROTHESISTE("Prothésiste"),
	PROTHESISTE_DENTAIRE("Prothésiste dentaire"),
	PSYCHANALYSTE("Psychanalyste"),
	PSYCHOLOGUE("Psychologue"),
	PSYCHOMOTRICIEN("Psychomotricien"),
	PUERICULTRICE("Puéricultrice"),
	REALISATEUR("Réalisateur"),
	RECEPTIONNISTE("Réceptionniste"),
	REDACTEUR_CHEF("Rédacteur chef"),
	REDACTEUR_EN_ASSURANCES("Rédacteur en assurances"),
	REDACTEUR_EN_CHEF("Rédacteur en chef"),
	REDACTEUR_TECHNIQUE("Rédacteur Technique"),
	REEDUCATEUR("Rééducateur"),
	REGISSEUR("Régisseur"),
	RELIEUR_DOREUR("Relieur-doreur"),
	RESPONSABLE_D_AGENCE_BANCAIRE("Responsable d'agence bancaire"),
	RESPONSABLE_D_EXPLOITATION("Responsable D'Exploitation"),
	RESPONSABLE_D_UN_SYSTEME_D_INFORMATION_METIER("Responsable D'Un Système D'Information Métier"),
	RESPONSABLE_DE_COMMUNICATION("Responsable de communication"),
	RESPONSABLE_DE_COMPTE("Responsable De Compte"),
	RESPONSABLE_DE_MARKETING_OPERATIONNEL("Responsable De Marketing Opérationnel"),
	RESPONSABLE_DE_SERVICE_INFORMATIQUE("Responsable De Service Informatique"),
	RESPONSABLE_DES_ETUDES("Responsable Des Études"),
	RESPONSABLE_LOGISTIQUE("Responsable logistique"),
	RESPONSABLE_MARKETING("Responsable marketing"),
	RESPONSABLE_SECURITE_INFORMATIQUE("Responsable Sécurité Informatique"),
	SAGE_FEMME("Sage-Femme"),
	SAPEUR_POMPIER("Sapeur-pompier"),
	SAPEUR_POMPIER_VOLONTAIRE("Sapeur-Pompier Volontaire"),
	SCRIPTE("Scripte"),
	SECRETAIRE_ADMINISTRATIF("Secrétaire administratif"),
	SECRETAIRE_ADMINISTRATIF_DES_AFFAIRES_SANITAIRES_ET_SOCIALES("Secrétaire administratif des affaires sanitaires et sociales"),
	SECRETAIRE_ASSISTANTE("Secrétaire assistante"),
	SECRETAIRE_DE_MAIRIE("Secrétaire de Mairie"),
	SECRETAIRE_DE_REDACTION("Secrétaire de rédaction"),
	SECRETAIRE_JURIDIQUE("Secrétaire juridique"),
	SECRETAIRE_MEDICO_SOCIALE("Secrétaire médico-sociale"),
	SECRETARIAT_ADMINISTRATIF_D_ADMINISTRATION_CENTRALE("Secrétariat administratif d'administration centrale"),
	SECURITE_CIVILE("Sécurité civile"),
	SERVEUR_DE_RESTAURANT("Serveur de restaurant"),
	SKIPPEUR("Skippeur"),
	SOCIOLOGUE("Sociologue"),
	SOLIER_MOQUETTISTE("Solier moquettiste"),
	SOMMELIER("Sommelier"),
	SOUDEUR("Soudeur"),
	STANDARDISTE("Standardiste"),
	STENOTYPISTE("Stenotypiste"),
	STORY_BOARDER("Story-boarder"),
	STYLISTE("Styliste"),
	SUPERVISEUR_DE_HOT_LINE("Superviseur De Hot-Line"),
	TAXIDERMISTE("Taxidermiste"),
	TECHNICIEN("Technicien"),
	TECHNICIEN_BIOLOGISTE("Technicien biologiste"),
	TECHNICIEN_CHIMISTE("Technicien Chimiste"),
	TECHNICIEN_DE_FABRICATION("Technicien de fabrication"),
	TECHNICIEN_DE_L_EDUCATION_NATIONALE("Technicien de l'éducation nationale"),
	TECHNICIEN_DE_L_INTERVENTION_SOCIALE_ET_FAMILIALE("Technicien de l'intervention sociale et familiale"),
	TECHNICIEN_DE_LABO_PHOTO("Technicien de labo photo"),
	TECHNICIEN_DE_LABORATOIRE("Technicien de laboratoire"),
	TECHNICIEN_EN_ANALYSES_BIOMEDICALES("Technicien en analyses biomédicales"),
	TECHNICIEN_EN_MECANIQUE("Technicien en mécanique"),
	TECHNICIEN_FORESTIER("Technicien forestier"),
	TECHNICIEN_LIGNE_HAUTE_TENSION("Technicien ligne haute tension"),
	TECHNICIEN_MAINTENANCE_AUTO("Technicien maintenance auto"),
	TECHNICIEN_MICRO("Technicien Micro"),
	TECHNICIEN_RESEAU("Technicien Réseau"),
	TECHNICIEN_TRAITEMENT_DECHETS("Technicien traitement déchets"),
	TECHNICIENS_DE_RECHERCHE_ET_DE_FORMATION("Techniciens de recherche et de formation"),
	TELEVENDEUR("Télévendeur"),
	TOILETTEUR("Toiletteur"),
	TÔLIER("Tôlier"),
	TOURNEUR_FRAISEUR("Tourneur-fraiseur"),
	TRADER("Trader"),
	TRADUCTEUR("Traducteur"),
	TRAFFIC_MANAGER("Traffic Manager"),
	URBANISTE("Urbaniste"),
	VENDEUR_EN_MAGASIN("Vendeur en magasin"),
	VENDEUR_EN_MICRO_INFORMATIQUE("Vendeur En Micro-Informatique"),
	VERRIER("Verrier"),
	VETERINAIRE("Vétérinaire"),
	VITICULTEUR("Viticulteur"),
	VRP("VRP"),
	WEBDESIGNER("Webdesigner"),
	WEBMARKETEUR("Webmarketeur"),
	WEBMASTER("Webmaster"),
	WEBMESTRE("Webmestre"),
	WEBPLANNER("Webplanner");

	private final String nom;

	Emploi(String nom) {
		this.nom = nom;
	}

	public String getNom() {
		return this.nom;
	}

	public static Emploi getEmploi(String str) {
		Emploi[] emplois = Emploi.values();
		Emploi emploi = null;

		for (Emploi emp : emplois) {
			if (emp.getNom().equals(str)) {
				emploi = emp;
			}

		}
		return emploi;
	}

}
