package enumeration;

public enum Motif {
	ACCIDENT_VASCULAIRE_CEREBRAL("Accident vasculaire cérébral"),
	ANEMIE("Anémie"),
	ANEVRISME("Anévrisme"),
	ANGINE_DE_POITRINE("Angine de poitrine"),
	ANXIETE("Anxiété"),
	APPENDICITE("Appendicite"),
	ARTERITE("Artérite"),
	ARTHROSE("Arthrose"),
	ATTAQUES_CEREBRALES("Attaques cérébrales"),
	AUTISME("Autisme"),
	ALLERGIE("Allergie"),
	ASTHME("Asthme"),
	BOUFFEES_DE_CHALEUR("Bouffées de chaleur"),
	BRONCHITE("Bronchite"),
	BRONCHIOLITE("Bronchiolite"),
	BRONCHITE_DU_FUMEUR("Bronchite du fumeur"),
	BRÛLURES("Brûlures"),
	BRÛLURES_D_ESTOMAC("Brûlures d'estomac"),
	CANCER_DU_COLON("Cancer du colon"),
	CANCER_DE_L_OVAIRE("Cancer de l'ovaire"),
	CANCER_DU_COL_DE_L_UTERUS("Cancer du col de l'utérus"),
	CANCER_DU_PANCREAS("Cancer du pancréas"),
	CANCER_DU_POUMON("Cancer du poumon"),
	CANCER_DU_SEIN("Cancer du sein"),
	CANCER_COLO_RECTAL("Cancer colo-rectal"),
	CANCER_DE_LA_VESSIE("Cancer de la vessie"),
	CANCER_DU_TESTICULE("Cancer du testicule"),
	CATARACTE("Cataracte"),
	CHIMIOTHERAPIE("Chimiothérapie"),
	CHOC_TRAUMATIQUE("Choc traumatique"),
	CHOC_ANAPHYLACTIQUE("Choc anaphylactique"),
	CHOLERA("Choléra"),
	CHLAMYDIA("Chlamydia"),
	COLIQUE_NEPHRETIQUE("Colique néphrétique"),
	COLITES_INFLAMMATOIRES("Colites inflammatoires"),
	COLOPATHIE("Colopathie"),
	COMA("Coma"),
	CONJONCTIVITE("Conjonctivite"),
	MIGRAINES("Migraines"),
	CRISE_DE_FOIE("Crise de foie"),
	CYSTITE("Cystite"),
	CHOLESTEROL("Cholestérol"),
	DIARRHEES("Diarrhées"),
	DIFFICULTES_RESPIRATOIRES("Difficultés respiratoires"),
	DOULEUR_POITRINE("Douleur poitrine"),
	DOULEUR_CHRONIQUE("Douleur chronique"),
	DOULEUR_MUSCULAIRE("Douleur musculaire"),
	DOULEUR_ABDOMINALE("Douleur abdominale"),
	DOULEUR_GENOU("Douleur genou"),
	DOULEUR_ESTOMAC("Douleur estomac"),
	DOULEURS_DU_SEIN("Douleurs du sein"),
	DOULEURS_ARTICULAIRES("Douleurs articulaires"),
	DIABETE_DE_TYPE_1("Diabète de type 1"),
	DIABETE_DE_TYPE_2E("Diabète de type 2E"),
	ECZEMA("Eczéma"),
	EMBOLIE_PULMONAIRE("Embolie pulmonaire"),
	ENTORSES("Entorses"),
	ENTORSE_DU_GENOU("Entorse du genou"),
	ENTORSE_DE_LA_CHEVILLE("Entorse de la cheville"),
	EPILEPSIE("Epilepsie"),
	ETAT_DE_CHOC("Etat de choc"),
	FATIGUE("Fatigue"),
	FATIGUE_VISUELLE("Fatigue visuelle"),
	FIBROME("Fibrome"),
	FIEVRE_JAUNE("Fièvre jaune"),
	FRACTURE_DU_BRAS("Fracture du bras"),
	FRACTURE_DU_POIGNET("Fracture du poignet"),
	FRACTURE_DE_LA_CLAVICULE("Fracture de la clavicule"),
	GASTRO_ENTERITE("Gastro-entérite"),
	GLAUCOME("Glaucome"),
	GOUTTE("Goutte"),
	GRIPPE("Grippe"),
	GRIPPE_AVIAIRE("Grippe aviaire"),
	GRIPPE_PORCINE("Grippe porcine"),
	GRIPPE_A("Grippe A"),
	HEMORROIDES("Hémorroides"),
	HEPATITE_A("Hépatite A"),
	HEPATITE_B("Hépatite B"),
	HEPATITE_C("Hépatite C"),
	HERNIE_DISCALE("Hernie discale"),
	HERPES("Herpes"),
	HYPERTENSION("Hypertension"),
	HYSTERIE("Hystérie"),
	INDIGESTION("Indigestion"),
	INFARCTUS("Infarctus"),
	INFARCTUS_DU_MYOCARDE("Infarctus du myocarde"),
	INFECTION_URINAIRE("Infection urinaire"),
	INFECTIONS_NOSOCOMIALES("Infections nosocomiales"),
	INSUFFISANCE_CARDIAQUE("Insuffisance cardiaque"),
	INSUFFISANCE_RENALE("Insuffisance rénale"),
	INSUFFISANCE_RESPIRATOIRE("Insuffisance respiratoire"),
	INSUFFISANCE_VEINEUSE("Insuffisance veineuse"),
	INTOXICATION_AU_PLOMB("Intoxication au plomb"),
	INTOXICATION_ALIMENTAIRE("Intoxication alimentaire"),
	NTOXICATION_MEDICAMENTEUSE("ntoxication médicamenteuse"),
	JAMBES_LOURDES("Jambes lourdes"),
	KYSTE("Kyste"),
	KYSTE_DE_L_OVAIRE("Kyste de l'ovaire"),
	LEGIONELLOSE("Légionellose"),
	LEPRE("Lèpre"),
	LEUCEMIE_LYMPHOÏDE("Leucémie lymphoïde"),
	LOMBALGIE("Lombalgie"),
	LUMBAGO("Lumbago"),
	LUXATION("Luxation"),
	LUXATION_DE_HANCHE("Luxation de hanche"),
	LYMPHOME("Lymphome"),
	MALAISE_CARDIAQUE("Malaise cardiaque"),
	MALARIA("Malaria"),
	MAL_DE_DOS("Mal de dos"),
	MAL_DES_TRANSPORTS("Mal des transports"),
	MALADIE_RARE("Maladie rare"),
	MENINGITE("Méningite"),
	MONONUCLEOSE("Mononucléose"),
	MUCOVISCIDOSE("Mucoviscidose"),
	MORSURE("Morsure"),
	MIGRAINE("Migraine"),
	MYCOSES("Mycoses"),
	NAUSEES("Nausées"),
	NEVRALGIE("Névralgie"),
	OBESITE("Obésité"),
	OEDEME_PULMONAIRE("Oedème pulmonaire"),
	ONGLE_INCARNE("Ongle incarné"),
	OSTEOPOROSE("Ostéoporose"),
	PALUDISME("Paludisme"),
	PAPILLOMAVIRUS("Papillomavirus"),
	PARALYSIE_FACIALE("Paralysie faciale"),
	PHLEBITE("Phlébite"),
	POLYARTHRITE_RHUMATOIDE("Polyarthrite rhumatoide"),
	PSORIASIS("Psoriasis"),
	REGLES_DOULOUREUSES("Règles douloureuses"),
	REGLES_HEMORRAGIQUES("Règles hémorragiques"),
	RHINITE("Rhinite"),
	RHUMATISMES("Rhumatismes"),
	RHUME("Rhume"),
	ROUGEOLE("Rougeole"),
	SAIGNEMENTS("Saignements"),
	SCLEROSE_EN_PLAQUES("Sclérose en plaques"),
	SCOLIOSE("Scoliose"),
	SIDA("Sida"),
	SINUSITE("Sinusite"),
	SPASMOPHILIE("Spasmophilie"),
	SPONDYLARTHRITE("Spondylarthrite"),
	SURDITE("Surdité"),
	SYNCOPE("Syncope"),
	SYPHILIS("Syphilis"),
	TENDINITE("Tendinite"),
	TETANOS("Tétanos"),
	THROMBOSE("Thrombose"),
	THYROIDE("Thyroide"),
	TORTICOLIS("Torticolis"),
	TOUX("Toux"),
	ULCERE("Ulcère"),
	ULCERE_GASTRO_DUODENAL("Ulcère gastro-duodénal"),
	ULCERE_DE_L_ESTOMAC("Ulcère de l'estomac"),
	ULCERE_DIGESTIF("Ulcère digestif"),
	URTICAIRE("Urticaire"),
	VARICELLE("Varicelle"),
	VARICES("Varices"),
	VERS_INTESTINAUX("Vers intestinaux");


	private final String nom;

	Motif(String nom) {
		this.nom = nom;
	}

	public String getNom() {
		return this.nom;
	}

	public static Motif getMotif(String str) {
		Motif[] motifs = Motif.values();
		Motif motif = null;

		for (Motif mot : motifs) {
			if (mot.getNom().equals(str)) {
				motif = mot;
			}

		}
		return motif;
	}

}
